all_embeddings: true
aux_loss_lambda: 0.3
cell_warmup_epochs: 10
cell_warmup_lr_factor: 0.1
cell_warmup_start: 50
dropout: 0.25
frozen_backbone: Virchow2
hidden_dim: 1280
hidden_dim_2: 256
input_dim: 2560
instance_batch_size: 1024
loss: bce
lr: 0.0005
model_type: hierarchical
n_classes: 1
pooling: sum
scale_drop_p: 0.15
top_k: 128
use_all_cells: false
weight_decay: 1.0e-05
